"""Op log -> OpenSCAD source.

Each AddPrimitive becomes a (translated) primitive expression; each Boolean
folds the with-expression into the target's expression as
`union()/difference() { target; with; }`. The result is one .scad file the
user can open in real OpenSCAD and see the same geometry.
"""
from __future__ import annotations

from typing import Iterable

from .ops import AddPrimitive, Boolean, Op


def _fmt(v: float) -> str:
    if abs(v - round(v)) < 1e-9:
        return f"{int(round(v))}"
    return f"{v:.6f}".rstrip("0").rstrip(".")


def _vec(v: Iterable[float]) -> str:
    return "[" + ", ".join(_fmt(float(x)) for x in v) + "]"


def _primitive_expr(kind: str, params: dict) -> str:
    if kind == "cube":
        return f"cube(size={_vec(params['size'])});"
    if kind == "sphere":
        seg = int(params.get("segments", 32))
        return f"sphere(r={_fmt(params['radius'])}, $fn={seg});"
    if kind == "cylinder":
        seg = int(params.get("segments", 32))
        return (
            f"cylinder(h={_fmt(params['height'])}, "
            f"r={_fmt(params['radius'])}, $fn={seg});"
        )
    raise ValueError(f"unknown primitive kind: {kind!r}")


def _wrap_translate(expr: str, offset: tuple[float, float, float]) -> str:
    if offset == (0.0, 0.0, 0.0):
        return expr
    return f"translate({_vec(offset)}) {expr}"


def render(ops: list[Op]) -> str:
    """Render an op log to OpenSCAD source.

    Anchors are resolved exactly as scene.py does — by computing each node's
    bbox at the time its anchor target was last updated. We mirror that here
    by maintaining (expr, bbox) per id and updating both as ops apply.
    """
    # Late import to avoid a cycle at module import time.
    from . import kernel as k
    from .scene import _primitive_self_center, _primitive_manifold, resolve_anchor, Node

    exprs: dict[str, str] = {}
    nodes: dict[str, Node] = {}
    order: list[str] = []

    for op in ops:
        if isinstance(op, AddPrimitive):
            base = _primitive_expr(op.kind, op.params)
            m = _primitive_manifold(op.kind, op.params)
            if op.anchor_to is not None:
                target = nodes[op.anchor_to]
                anchor_pt = resolve_anchor(target, op.anchor)
                self_c = _primitive_self_center(op.kind, op.params)
                offset = (
                    anchor_pt[0] - self_c[0] + op.offset[0],
                    anchor_pt[1] - self_c[1] + op.offset[1],
                    anchor_pt[2] - self_c[2] + op.offset[2],
                )
                m = k.translate(m, offset)
            else:
                offset = op.offset
                if offset != (0.0, 0.0, 0.0):
                    m = k.translate(m, offset)
            expr = _wrap_translate(base, offset)
            exprs[op.node_id] = expr
            nodes[op.node_id] = Node(
                id=op.node_id, kind=op.kind, params=dict(op.params), manifold=m
            )
            order.append(op.node_id)
        elif isinstance(op, Boolean):
            t_expr = exprs[op.target_id]
            w_expr = exprs[op.with_id]
            scad_op = "union" if op.kind == "union" else "difference"
            new_expr = f"{scad_op}() {{ {t_expr} {w_expr} }}"
            exprs[op.target_id] = new_expr
            target = nodes[op.target_id]
            with_node = nodes[op.with_id]
            if op.kind == "union":
                target.manifold = k.union(target.manifold, with_node.manifold)
            else:
                target.manifold = k.difference(target.manifold, with_node.manifold)
            if op.consume_with:
                del exprs[op.with_id]
                del nodes[op.with_id]
                order.remove(op.with_id)
        else:
            raise TypeError(f"unknown op: {type(op).__name__}")

    body = "\n  ".join(exprs[nid] for nid in order) if order else "// empty"
    return (
        "// Generated by fastcad. Open in OpenSCAD as-is.\n"
        "module fastcad_scene() {\n"
        f"  {body}\n"
        "}\n"
        "fastcad_scene();\n"
    )
